name: Backend CI

on:
    pull_request:
        branches:
            - main
        types: [ opened ]
        paths:
            - 'backend/**'
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install pipenv
                run: |
                    python -m pip install --upgrade pip
                    pip install pipenv
                working-directory: ./backend

            -   name: Install dependencies and lint
                run: |
                    pipenv install
                    pipenv run lint
                working-directory: ./backend

    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install pipenv
                run: |
                    python -m pip install --upgrade pip
                    pip install pipenv
                working-directory: ./backend

            -   name: Install dependencies and test
                run: |
                    pipenv install
                    pipenv run test
                working-directory: ./backend

    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install pipenv
                run: |
                    python -m pip install --upgrade pip
                    pip install pipenv
                working-directory: ./backend

            -   name: Install dependencies and build
                run: |
                    pipenv install
                    docker build --tag mp-backend:latest .
                working-directory: ./backend