name: Backend CD

on:
    workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: backend

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install pipenv
                run: |
                    python -m pip install --upgrade pip
                    pip install pipenv
                working-directory: ./backend

            -   name: Install dependencies and lint
                run: |
                    pipenv install
                    pipenv run lint
                working-directory: ./backend

    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install pipenv
                run: |
                    python -m pip install --upgrade pip
                    pip install pipenv
                working-directory: ./backend

            -   name: Install dependencies and test
                run: |
                    pipenv install
                    pipenv run test
                working-directory: ./backend


    push-to-ecr:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}