name: Frontend CI

on:
    pull_request:
        branches:
            - main
        types: [ opened ]
        paths:
            - 'frontend/**'
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        container:
            image: node:latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Cache node modules
                id: cache-npm
                uses: actions/cache@v3
                env:
                    cache-name: cache-node-modules
                with:
                    # npm cache files are stored in `~/.npm` on Linux/macOS
                    path: ~/.npm
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-

            -   name: npm install dependencies
                run: npm ci
                working-directory: ./frontend

            -   name: npm lint
                run: npm run lint
                working-directory: ./frontend

    test:
        runs-on: ubuntu-latest
        container:
            image: node:latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Cache node modules
                id: cache-npm
                uses: actions/cache@v3
                env:
                    cache-name: cache-node-modules
                with:
                    # npm cache files are stored in `~/.npm` on Linux/macOS
                    path: ~/.npm
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-

            -   name: npm install dependencies
                run: npm ci
                working-directory: ./frontend

            -   name: npm test
                run: npm test
                working-directory: ./frontend

    build:
        runs-on: ubuntu-latest
        container:
            image: node:latest
        needs: [ lint, test ]

        steps:
            -   name: Install Docker
                run: |
                    sudo apt-get update
                    sudo apt-get install -y docker.io

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Cache node modules
                id: cache-npm
                uses: actions/cache@v3
                env:
                    cache-name: cache-node-modules
                with:
                    # npm cache files are stored in `~/.npm` on Linux/macOS
                    path: ~/.npm
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-

            -   name: npm install dependencies
                run: npm ci
                working-directory: ./frontend

            -   name: build
                run: |
                    docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
                working-directory: ./frontend